### PR TITLE
close pending opened streams in SevenZipArchiveHandler.kt

### LINKED ISSUE #14: TAR-achive is not deletable after browsing unless closing IDEA
Hi,
I really love this Plugin. It's very useful. But unfortunately when I've opened a TAR-archive, it is no more deletable or can be overwritten by any code. This is just possible when exiting IDEA.

The error is an IOException. It feels like the archive doesn't get closed after showing the content in the tree.
Kind regards, Thomas

### PR DESCRIPTION
**Pull request by gun88**
fix #14

### CODE REVIEW

**Comment by gun88** [comment]
@b3er I have pushed also the .idea/misc.xml file but now I've restored it

File: src/main/kotlin/com/github/b3er/idea/plugins/arc/browser/base/sevenzip/SevenZipArchiveHandler.kt [hunk 1]
```diff
@@ -31,6 +31,11 @@ open class SevenZipArchiveHandler(path: String) :
                 }
             }
         }
+        private fun toArchive(raf: RandomAccessFile): IInArchive? {
+            val archive = SevenZip.openInArchive(null, RandomAccessFileInStream(raf))
+            raf.close()
```
Comment (leonard84) [inline src/main/kotlin/com/github/b3er/idea/plugins/arc/browser/base/sevenzip/SevenZipArchiveHandler.kt:36]: Shouldn't you use `use` instead? https://www.baeldung.com/kotlin-try-with-resources
